language: java
jdk:
  - openjdk11
addons:
  apt:
    packages:
    - libaio1
notifications:
  email: false
#install: mvn install -Pskip-tests
#script: mvn test -B -f native-helper/pom.xml -Dtest=SubprocessPipingTest
script: mvn verify -B
