version: 0.{build}
install:
  - cmd: echo %JAVA_HOME%
  - cmd: >-
      set JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
      set MAVEN_VERSION=3.5.0
      choco install maven -version %MAVEN_VERSION%
      set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
      mvn --version
build_script:
  - cmd: mvn install --quiet --batch-mode
