version: 1.0.{build}
build_script:
- cmd: >-
    set MAVEN_VERSION=3.5.0

    choco install maven -version %MAVEN_VERSION%

    set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

    mvn install --quiet --batch-mode
