version: 0.{build}
install:
  - cmd: echo %JAVA_HOME%
  - cmd: >-
      set MAVEN_VERSION=3.5.0

      choco install maven -version %MAVEN_VERSION%

      set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
build_script:
  - cmd: mvn install --quiet --batch-mode
