version: 1.0.{build}
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
build_script:
- cmd: >-
    java --version

    mvn --version

    python --version

    echo "PATH=%PATH%"

    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    mvn install --quiet --batch-mode
